# DeluxeMenus 1.14.1-Release main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/helpchat-plugins/deluxemenus

check_updates: true
debug: LOW
use_admin_commands_in_menus_list: false
menus_list_page_size: 10
metas_list_page_size: 15
gui_menus:
  basics_menu:
    file: basics_menu.yml
  advanced_menu:
    file: advanced_menu.yml
  requirements_menu:
    file: requirements_menu.yml
  donator_shop:
    file: donator_shop.yml
  main_menu:
    file: main_menu.yml
