# Update notification on login
# Can be disabled when no internet connection is available
update-notify: true

# Automatically saves player data at a set interval.
# Reload required when edited
auto-save:
  enabled: true
  interval: 1800 # In seconds (1800 = 30 minutes)
  log: true

# Will verbose to the console whenever
# data is saved/loaded from the SQL database.
debug: false

# MySQL Support
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: minecraft
  user: mmolover
  pass: ILoveAria
  maxPoolSize: 10
  maxLifeTime: 300000
  connectionTimeOut: 10000
  leakDetectionThreshold: 150000
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

# Amount of slots in the inventory - has to be a multiple of 9.
# Remember to update the slot numbers in items.yml after changing this option.
inventory-slots: 54

# Enable this option to move the accessory slots to the player
# inventory. A tutorial is available on the resource page.
# Requires a server reload when changed.
no-custom-inventory: false

# This prevents a known dupe bug so it is strongly
# recommended to keep this set to true.
disable-equiping-stacked-items: true

# Items will drop (when keep-inventory is disabled) on death.
# Requires a server reload when changed.
drop-on-death: true

# Available modules:
# - aureliumskills (level only)
# - battlelevels (level only)
# - default (uses player's exp bar, level only)
# - fabled
# - heroes
# - mcmmo (level only)
# - mcrpg (level only)
# - mmocore
# - proskillapi
# - racesandclasses
# - rpgplayerleveling (level only)
# - skillapi
# - skills
# - skillspro
level-module: aureliumskulls
class-module: default

# When enabled, MMOInventory with automatically generate the
# necessary files for Oraxen inside of the following file:
#     ~/plugins/Oraxen/items/mmoinventory-hook.yml
#
# Files are generated on server startup, so make sure you
# restart your server when editing this option.
generate-oraxen-files: true

# Adds a static to the player's inventory.
# Opens up the custom inventory when clicked.
# Requires a server reload when changed.
inventory-button:
  enabled: false
  slot: 9
  item:
    material: CHEST
    name: '&6Custom Inventory'
    lore:
      - ''
      - '&eClick to open.'
    # custom-model-data: 1
    # skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg5Yjk4ZjA0YzMyMjdkMzdkMzE5YmJjZmZjNTFmNTJlNzhkOTZhMDViMTI4NTJkMWI0NjRiYjc0MDhhNzgxMCJ9fX0=

# Enable/disable auto resource pack download. Requires a server reload when changed.
# Default RP: https://www.dropbox.com/s/1lftxmzh0q4b5yu/mmoinv_rp_4.zip?dl=1
resource-pack:
  enabled: false
  url: https://www.dropbox.com/s/1lftxmzh0q4b5yu/mmoinv_rp_4.zip?dl=1
  delay: 20

  # Kick player if he does not accept the server resource pack or
  # if the download failed. Requires a server reload when changed.
  kick:
    enabled: false
    message: 'Please accept server resource pack!'