# Only turn this on if you're asked to
# Might spam your console and/or chat ;-)
debug: false

# Do not change this!
version: 1

# Example configuration
command:
  # Name of the Command.
  command1:
    # Key to press
    # f/q 
    key: f  # Default f

    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: true  # Default true

    # Which command should be executed?
    # You can also use PlaceholderAPI here
    # Enter without /
    commandList:
      - 메뉴  

    # Stopping item drop or hand swap from happening
    cancel: true  # Default false

    # Should the command be executed as the Server?
    executeAsServer: false  # default false