debug: false
auto-save-time: 300
location-provide-time: 1
debug-level: assets
metrics: true
version-check: true
number-format: '#,###.#'
tick-speed: 1
namespace: betterhud
default-font-name: font.ttf
bossbar-line: 1
bossbar-resource-pack-line: 0
merge-boss-bar: true
disable-to-bedrock-player: true
build-folder-location: BetterHud/build
pack-type: zip
enable-protection: false
enable-self-host: false
force-update: false
self-host-ip: 211.104.98.211
self-host-port: 8193
merge-other-folders: []
loading-head: random
default-hud:
- test_hud
default-popup: []
default-compass: []
load-minecraft-default-textures: false
included-minecraft-list:
- block
- item
resourcepack-obfuscation: false
clear-build-folder: true
use-legacy-format: false
legacy-serializer: ampersand
minecraft-jar-version: bukkit
remove-default-hotbar: false
disable-legacy-offset: true
merge-with-external-resources: true
