# If enabled, the plugin will check for available updates when enabled
checkUpdates: true
# Informs a player know when they are bypassing a cooldown
sendBypassMessage: true
# Database support
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: name
  username: root
  password: password
version: 3.0.8
