# -----------------------
# DisableTotems config file
# author: aphonix
# discord: https://discord.gg/zYVtWxEar8
# -----------------------

DisableTotemMessage: "&b&l[DT] &fTOTEM_OF_UNDYING is disabled on this server."